INSERT INTO RATING_MPA (RATING_ID, NAME) VALUES (1, 'G');
INSERT INTO RATING_MPA (RATING_ID, NAME) VALUES (2, 'PG');
INSERT INTO RATING_MPA (RATING_ID, NAME) VALUES (3, 'PG-13');
INSERT INTO RATING_MPA (RATING_ID, NAME) VALUES (4, 'R');
INSERT INTO RATING_MPA (RATING_ID, NAME) VALUES (5, 'NC-17');

INSERT INTO GENRE (GENREID, NAME) VALUES (1, 'Комедия');
INSERT INTO GENRE (GENREID, NAME) VALUES (2, 'Драма');
INSERT INTO GENRE (GENREID, NAME) VALUES (3, 'Мультфильм');
INSERT INTO GENRE (GENREID, NAME) VALUES (4, 'Триллер');
INSERT INTO GENRE (GENREID, NAME) VALUES (5, 'Документальный');
INSERT INTO GENRE (GENREID, NAME) VALUES (6, 'Боевик');