INSERT INTO GENRE_FILM (Film_id, GENRE_ID) VALUES (1, 3);
INSERT INTO GENRE_FILM (Film_id, GENRE_ID) VALUES (2, 1);
INSERT INTO GENRE_FILM (Film_id, GENRE_ID) VALUES (3, 2);
INSERT INTO GENRE_FILM (Film_id, GENRE_ID) VALUES (2, 2);