INSERT INTO LIKES (Film_id, USER_ID) VALUES (1, 2);
INSERT INTO LIKES (Film_id, USER_ID) VALUES (1, 3);
INSERT INTO LIKES (Film_id, USER_ID) VALUES (1, 1);
INSERT INTO LIKES (Film_id, USER_ID) VALUES (2, 3);
INSERT INTO LIKES (Film_id, USER_ID) VALUES (3, 3);
INSERT INTO LIKES (Film_id, USER_ID) VALUES (3, 2);